### ISSUE TITLE
Clearing the Trace

### ISSUE THREAD

**Issue by dbGIS** [GreatLakesCommission/barriers#8]
if you select the barrier just downstream of Cheboygan dam before selecting Cheboygan dam, when you go to clear the trace, the first small segment is not cleared.

**Comment by hellocomrade** [comment]
Old upstream trace result is not removed if followed by a extreme-large-upstream traceing

**Comment by hellocomrade** [comment]
I believe this is a feature instead of bug: when you choose an adjacent barrier from the previous tracing, the previous segments will remain and be combined with the new result.

**Comment by dbGIS** [comment]
That is a feature but the Clear Trace button doesn't remove the small segment with the extremely large one and the button is greyed out after that, so the small portion of the trace is stuck there.

**Comment by hellocomrade** [comment]
Start from Little Black River Structure D, and then go downstream at 'LITTLE BLACK RIVER STRUCTURE C DAM', you will see what I am talking about...

**Comment by hellocomrade** [comment]
OK, I know what you meant now!

**Comment by hellocomrade** [comment]
This issue is a bug in the javascript file: app.js. When the cleanup occurs, vector layer was not emptied if a wms cache layer existed at the same time. This bug has been fixed.
